### ISSUE TITLE
Import / Export tab

### ISSUE THREAD

**Issue by CoolDotty** [CoolDotty/fvf-decks#3]
- [ ] Shows cards in the same order as how they appear in game.
  - [ ] All cards
  - [ ] In chunks of two rows, 4 in total
  - [ ] Sorted by ID
  - [ ] Keep the cards small, so it's easy to use on another monitor without alt tabbing
- [ ] (Assume there isn't an official API added after this ticket was made)

**Comment by x3cca** [comment]
Closed by https://github.com/CoolDotty/fvf-decks/pull/17
