### ISSUE TITLE
Add copy link / share button

### ISSUE THREAD

**Issue by CoolDotty** [CoolDotty/fvf-decks#8]
in the top bar somewhere probably.

Do a little popup effect that says "Copied!" or something

**Comment by devkennyy** [comment]
I'd like to be assigned!

**Comment by x3cca** [comment]
It's all good, I'm almost finished up with it. I'll be pushing it along with a couple component refactors that should help with other issues though!

**Comment by devkennyy** [comment]
No problem! Look forward to seeing it :)

**Comment by x3cca** [comment]
Done! https://github.com/KarlTheCool/fvf-decks/commit/c043a1dd239110c506f41022ce1280423b105eb8
