### ISSUE TITLE
Change Filter Radios to Icons

### ISSUE THREAD

**Issue by CoolDotty** [CoolDotty/fvf-decks#9]
- [ ] Use the provided sprite atlas ripped from the game
- [ ] Make sure to add `alt` attributes with the name for the filter

![atlas](https://github.com/KarlTheCool/fvf-decks/assets/10494276/e4370595-bef7-4793-962a-29fc278ebf55)

**Comment by devkennyy** [comment]
I'd like to be assigned for this!
